#!/usr/bin/env bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"

auth_service_filter() {
  declare desc="calls user-service plugin trigger"
  declare SERVICES=("$@")
  local user_auth_count

  if [[ "${#SERVICES[@]}" -eq 0 ]]; then
    return
  fi

  user_auth_count="$(find "$PLUGIN_PATH"/enabled/*/user-auth-service 2>/dev/null | wc -l)"

  # no plugin trigger exists
  if [[ $user_auth_count == 0 ]]; then
    # echo out all the services since there is no plugin trigger
    for SERVICE in "${SERVICES[@]}"; do
      [[ -n "$SERVICE" ]] && echo "$SERVICE"
    done
    return 0
  fi

  # this plugin trigger exists in the core `20_events` plugin
  if [[ "$user_auth_count" == 1 ]] && [[ -f "$PLUGIN_PATH"/enabled/20_events/user-auth-service ]]; then
    # echo out all the services since there is no valid plugin trigger
    for SERVICE in "${SERVICES[@]}"; do
      [[ -n "$SERVICE" ]] && echo "$SERVICE"
    done
    return 0
  fi

  export SSH_USER=${SSH_USER:=$USER}
  export SSH_NAME=${NAME:="default"}
  # the output of this trigger should be all the services a user has access to
  plugn trigger user-auth-service "$SSH_USER" "$SSH_NAME" "$PLUGIN_COMMAND_PREFIX" "${SERVICES[@]}"
}

fn-services-list() {
  declare desc="prints a filtered list of all local apps"
  declare FILTER="$1"
  local services=()

  pushd "$PLUGIN_DATA_ROOT" >/dev/null
  for f in *; do
    [[ -d $f ]] || continue
    services+=("$f")
  done
  popd >/dev/null 2>&1 || pushd "/tmp" >/dev/null

  if [[ "${#services[@]}" -eq 0 ]]; then
    return
  fi

  if [[ "$FILTER" == "false" ]]; then
    for service in "${services[@]}"; do
      if [[ -n "$service" ]]; then
        echo "$service"
      fi
    done
    return
  fi

  for service in $(auth_service_filter "${services[@]}" 2>/dev/null); do
    if [[ -n "$service" ]]; then
      echo "$service"
    fi
  done
}

get_service_name() {
  declare desc="retrieve a docker service label"
  declare SERVICE="$1"
  echo "dokku.${PLUGIN_COMMAND_PREFIX}.$SERVICE"
}

is_container_status() {
  declare desc="return 0 or 1 depending upon whether a given container has a certain status"
  declare CID="$1" STATUS="$2"
  local TEMPLATE="{{.State.$STATUS}}"
  local CONTAINER_STATUS=$("$DOCKER_BIN" container inspect -f "$TEMPLATE" "$CID" 2>/dev/null || true)

  if [[ "$CONTAINER_STATUS" == "true" ]]; then
    return 0
  fi
  return 1
}

is_implemented_command() {
  declare desc="return true if value ($1) is in list (all other arguments)"
  declare CMD="$1"
  CMD="$(echo "$CMD" | cut -d ':' -f2)"

  if [[ ${#PLUGIN_UNIMPLEMENTED_SUBCOMMANDS[@]} -eq 0 ]]; then
    return 0
  fi

  local e
  for e in "${PLUGIN_UNIMPLEMENTED_SUBCOMMANDS[@]}"; do
    [[ "$e" == "$CMD" ]] && return 1
  done
  return 0
}

service_exists() {
  declare desc="returns 0 or 1 depending on whether service exists or not"
  declare SERVICE="$1"
  [[ -z "$SERVICE" ]] && return 1
  [[ -d "$PLUGIN_DATA_ROOT/$SERVICE" ]] && return 0
  return 1
}

service_parse_args() {
  declare desc="cli arg parser"
  local next_index=1
  local skip=false
  local args=("$@")

  for arg in "$@"; do
    shift
    case "$arg" in
      "--alias") set -- "$@" "-a" ;;
      "--config-options") set -- "$@" "-c" ;;
      "--custom-env") set -- "$@" "-C" ;;
      "--database") set -- "$@" "-d" ;;
      "--image-version") set -- "$@" "-I" ;;
      "--initial-network") set -- "$@" "-N" ;;
      "--image") set -- "$@" "-i" ;;
      "--memory") set -- "$@" "-m" ;;
      "--no-restart") set -- "$@" "-n" ;;
      "--password") set -- "$@" "-p" ;;
      "--post-create-network") set -- "$@" "-P" ;;
      "--post-start-network") set -- "$@" "-S" ;;
      "--querystring") set -- "$@" "-q" ;;
      "--restart-apps") set -- "$@" "-R" ;;
      "--root-password") set -- "$@" "-r" ;;
      "--shm-size") set -- "$@" "-s" ;;
      "--user") set -- "$@" "-u" ;;
      *) set -- "$@" "$arg" ;;
    esac
  done

  OPTIND=1
  while getopts "na:c:C:d:i:I:m:n:N:p:P:q:R:r:s:S:u:" opt; do
    case "$opt" in
      a)
        SERVICE_ALIAS="${OPTARG^^}"
        export SERVICE_ALIAS="${SERVICE_ALIAS%_URL}"
        ;;
      c)
        export PLUGIN_CONFIG_OPTIONS=$OPTARG
        ;;
      C)
        export SERVICE_CUSTOM_ENV=$OPTARG
        ;;
      d)
        export SERVICE_DATABASE=$OPTARG
        ;;
      i)
        export PLUGIN_IMAGE=$OPTARG
        ;;
      I)
        export PLUGIN_IMAGE_VERSION=$OPTARG
        ;;
      m)
        export SERVICE_MEMORY=$OPTARG
        ;;
      n)
        export SERVICE_RESTART_APPS=false
        ;;
      N)
        export SERVICE_INITIAL_NETWORK=$OPTARG
        ;;
      p)
        export SERVICE_PASSWORD=$OPTARG
        ;;
      P)
        export SERVICE_POST_CREATE_NETWORK=$OPTARG
        ;;
      q)
        export SERVICE_QUERYSTRING=${OPTARG#"?"}
        ;;
      R)
        export SERVICE_RESTART_APPS=$OPTARG
        ;;
      r)
        export SERVICE_ROOT_PASSWORD=$OPTARG
        ;;
      s)
        export SERVICE_SHM_SIZE=$OPTARG
        ;;
      S)
        export SERVICE_POST_START_NETWORK=$OPTARG
        ;;
      u)
        export SERVICE_USER=$OPTARG
        ;;
    esac
  done
  shift "$((OPTIND - 1))" # remove options from positional parameters
}

service_version() {
  declare desc="display the running version for an image"
  declare SERVICE="$1"
  local SERVICE_NAME="$(get_service_name "$SERVICE")"
  "$DOCKER_BIN" container inspect -f '{{.Config.Image}}' "$SERVICE_NAME" 2>/dev/null || true
}

verify_service_name() {
  declare desc="verify that a service exists"
  declare SERVICE="$@"

  if [[ -z "$SERVICE" ]]; then
    dokku_log_fail "SERVICE must not be empty"
  fi

  if [[ ! -d "$PLUGIN_DATA_ROOT/$SERVICE" ]]; then
    dokku_log_fail "$PLUGIN_SERVICE service $SERVICE does not exist"
  fi

  SERVICE="$(auth_service_filter "$SERVICE")"
  if [[ -z "$SERVICE" ]]; then
    dokku_log_fail "$PLUGIN_SERVICE service $SERVICE does not exist"
  fi

  return 0
}

