#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/common-functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

service-backup-unset-encryption-cmd() {
  declare desc="unset encryption for future backups of the $PLUGIN_SERVICE service"
  local cmd="$PLUGIN_COMMAND_PREFIX:backup-unset-encryption" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare SERVICE="$1"
  is_implemented_command "$cmd" || dokku_log_fail "Not yet implemented"

  "${DOKKU_LIB_ROOT}/data/${PLUGIN_COMMAND_PREFIX}/dokku-datastore" backup-unset-encryption "$PLUGIN_COMMAND_PREFIX" "$@"
}

service-backup-unset-encryption-cmd "$@"
