#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/common-functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

service-connect-cmd() {
  declare desc="connect to the service via the $PLUGIN_COMMAND_PREFIX connection tool"
  local cmd="$PLUGIN_COMMAND_PREFIX:connect" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare SERVICE="$1"

  "${DOKKU_LIB_ROOT}/data/${PLUGIN_COMMAND_PREFIX}/dokku-datastore" connect "$PLUGIN_COMMAND_PREFIX" "$@"
}

service-connect-cmd "$@"
