#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

service-unlink-cmd() {
  #E you can unlink a $PLUGIN_COMMAND_PREFIX service
  #E > NOTE: this will restart your app and unset related environment variables
  #E dokku $PLUGIN_COMMAND_PREFIX:unlink lollipop playground
  #A service, service to run command against
  #A app, app to run command against
  #F -n|--no-restart "false", whether or not to restart the app on unlink (default: true)
  declare desc="unlink the $PLUGIN_SERVICE service from the app"
  local cmd="$PLUGIN_COMMAND_PREFIX:unlink" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare SERVICE="$1" APP="$2" UNLINK_FLAGS_LIST=("${@:3}")
  APP=${APP:="$DOKKU_APP_NAME"}

  "${DOKKU_LIB_ROOT}/data/${PLUGIN_COMMAND_PREFIX}/dokku-datastore" unlink "$PLUGIN_COMMAND_PREFIX" "$SERVICE" "$APP" "${UNLINK_FLAGS_LIST[@]}"
}

service-unlink-cmd "$@"
